language: cpp
compiler: clang
dist: bionic
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
script:
    - sudo ln -s /usr/bin/clang++  /usr/local/bin/clang++
    - export CXX=/usr/local/bin/clang++
    - clang++ -v && cmake --version
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
