language: cpp
compiler: g++
dist: bionic
os : linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
script:
    - export CXX=/usr/lib/gcc/x86_64-linux-gnu/8
    - clang++ -v && cmake --version
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
