language: cpp
compiler: g++
dist: bionic
os : linux

      
script:
    - g++ -v && cmake --version
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .
    - make test
