language: cpp
compiler: clang
dist: bionic
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
script:
    - export CXX=/usr/local/clang-7.0.0/bin
    - clang++ -v && cmake --version
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
